### ISSUE TITLE
ModuleNotFoundError: No module named 'settings_local'

### ISSUE THREAD

**Issue by ritomsonowal** [PGPerfFarm/pgperffarm#26]
I was trying to set up the project in my local but when I run-

`python manage.py makemigrations`

It shows the error -
`Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ritom/.virtualenvs/pgperffarm/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/ritom/.virtualenvs/pgperffarm/lib/python3.6/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/home/ritom/.virtualenvs/pgperffarm/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/ritom/.virtualenvs/pgperffarm/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ritom/.virtualenvs/pgperffarm/lib/python3.6/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/ritom/.virtualenvs/pgperffarm/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ritom/GSoC-2019/pgperffarm/web/pgperffarm/settings.py", line 7, in <module>
    from settings_local import *
ModuleNotFoundError: No module named 'settings_local'
`

If I comment out the import and paste all the contents of 'settings_local.py' file, It shows another import error for serializer in another file but I confirmed that the module was present in the right directory.
Any idea?

**Comment by pavanagrawal123** [comment]
Hi @ritomsonowal,

I think you're missing this step: 
Next, create a settings_local.py file:
`$ cp web/pgperffarm/settings_local.py.in web/pgperffarm/settings_local.py`
Can you please post the serializer error you are getting? Thanks

**Comment by ritomsonowal** [comment]
I did create settings_local.py.
Even edited it according to my Postgres database.

Here's the serializer import error - 
`/home/ritom/.virtualenvs/pgperffarm/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ritom/.virtualenvs/pgperffarm/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/ritom/.virtualenvs/pgperffarm/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/home/ritom/.virtualenvs/pgperffarm/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ritom/.virtualenvs/pgperffarm/lib/python3.6/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/home/ritom/.virtualenvs/pgperffarm/lib/python3.6/site-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/home/ritom/.virtualenvs/pgperffarm/lib/python3.6/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/ritom/.virtualenvs/pgperffarm/lib/python3.6/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/home/ritom/.virtualenvs/pgperffarm/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ritom/GSoC-2019/pgperffarm/web/apps/users/admin.py", line 8, in <module>
    from serializer import UserMachineSerializer
ModuleNotFoundError: No module named 'serializer'
`

**Comment by pavanagrawal123** [comment]
Oh I see you are running Python 3.6, use Python 2, and there shouldn't be an error

**Comment by ritomsonowal** [comment]
Thanks that did the task. There were still errors  while running `python manage.py makemigrations` and then `python manage.py migrate` (it said the users relation did not exist).
I had to specifically run those two commands for those apps (users, user_operaton). But it works now. Thanks!

**Comment by pavanagrawal123** [comment]
No worries @ritomsonowal  If you have any other questions, please be sure to ask!

**Comment by ritomsonowal** [comment]
Hi @pavanagrawal123 ,
I modified the readme to help anyone with the errors I faced. I created a pull request for the same. Can you look into it?
