### ISSUE TITLE
Django error when migrating

### ISSUE THREAD

**Issue by IlariaB** [PGPerfFarm/pgperffarm#27]
Hello,
I am trying to run the PGPerFarm on Mac OSX. Everything works fine with Postgres (I'm using Python3) until I try to execute the last instruction from readme, to sync with the database (python manage.py migrate). The given output is:

```
(pgperffarm) Ilas-MacBook-Air:web ila$ python manage.py migrate
/Users/ila/.virtualenvs/pgperffarm/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying admin.0001_initial...Traceback (most recent call last):
  File "/Users/ila/.virtualenvs/pgperffarm/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "users_userprofile" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/ila/.virtualenvs/pgperffarm/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/ila/.virtualenvs/pgperffarm/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/ila/.virtualenvs/pgperffarm/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/ila/.virtualenvs/pgperffarm/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/ila/.virtualenvs/pgperffarm/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/Users/ila/.virtualenvs/pgperffarm/lib/python3.6/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/ila/.virtualenvs/pgperffarm/lib/python3.6/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/ila/.virtualenvs/pgperffarm/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/ila/.virtualenvs/pgperffarm/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 93, in __exit__
    self.execute(sql)
  File "/Users/ila/.virtualenvs/pgperffarm/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 120, in execute
    cursor.execute(sql, params)
  File "/Users/ila/.virtualenvs/pgperffarm/lib/python3.6/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/ila/.virtualenvs/pgperffarm/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/ila/.virtualenvs/pgperffarm/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/ila/.virtualenvs/pgperffarm/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/ila/.virtualenvs/pgperffarm/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "users_userprofile" does not exist

```

The code is almost untouched, I just added my PG user to settings_local.py and added a few parenthesis on the print instructions and the imports to make them compatible with Py3. I'd rather not use Python2, since it gave me major issues with pip and PATH settings.

I just reinstalled PG (psql11.2), may this be the issue?

**Comment by aditya999123** [comment]
You should create migrations first for the app 'users'.

**Comment by IlariaB** [comment]
How do I exactly do that? The documentation is incomplete, and I'd prefer being sure about what I am doing. Anyway, I freshly reinstalled everything on a Debian9 environment and now when I try to make migrations it says:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.virtualenvs/pgperffarm/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/root/.virtualenvs/pgperffarm/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/root/.virtualenvs/pgperffarm/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.virtualenvs/pgperffarm/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/root/.virtualenvs/pgperffarm/local/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ila/pg/pgperffarm/web/apps/users/models.py", line 16, in <module>
    class UserProfile(AbstractUser):
  File "/root/.virtualenvs/pgperffarm/local/lib/python2.7/site-packages/django/db/models/base.py", line 254, in __new__
    'base class %r' % (field.name, name, base.__name__)
django.core.exceptions.FieldError: Local field 'username' in class 'UserProfile' clashes with field of similar name from base class 'AbstractUser'

```

Any advice or ideas on what is causing this?

**Comment by aditya999123** [comment]
try creating migrations with name of the app "python manage.py makemigrations users"

**Comment by IlariaB** [comment]
Gosh, it was that easy ^^ now it works smoothly! Thank you so much :)
